//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class fact
    {
        public int fact_id { get; set; }
        public string fact1 { get; set; }
        public Nullable<int> animal_id { get; set; }
    
        public virtual animal animal { get; set; }
    }
}
