//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class animals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public animals()
        {
            this.facts = new HashSet<facts>();
            this.pictures = new HashSet<pictures>();
            this.sounds = new HashSet<sounds>();
        }
    
        public int animal_id { get; set; }
        public string common_name { get; set; }
        public string scientific_name { get; set; }
        public byte[] qr_code { get; set; }
        public string tags { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> exhibit_id { get; set; }
    
        public virtual classes classes { get; set; }
        public virtual exhibits exhibits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facts> facts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pictures> pictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sounds> sounds { get; set; }
    }
}
