//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimalEntities : DbContext
    {
        public AnimalEntities()
            : base("name=AnimalEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<animals> animals { get; set; }
        public virtual DbSet<classes> classes { get; set; }
        public virtual DbSet<exhibits> exhibits { get; set; }
        public virtual DbSet<facts> facts { get; set; }
        public virtual DbSet<pictures> pictures { get; set; }
        public virtual DbSet<sounds> sounds { get; set; }
    }
}
